baseURL = 'https://www.tobiasschuerg.de'
defaultContentLanguage = 'de'
defaultContentLanguageInSubdir = false
title = 'tobiasschuerg.de'

# Disable unused features
disableKinds = ["taxonomy", "term", "RSS"]

[params]
  github_username = "tobiasschuerg"

[languages]
  [languages.de]
    languageCode = 'de-DE'
    languageName = 'Deutsch'
    title = 'tobiasschuerg.de'
    weight = 1
    [languages.de.params]
      description = "Sammelt digitalen Staub."
    [[languages.de.menu.main]]
      identifier = "projects"
      name = "Projekte"
      url = "/"
      weight = 10
    [[languages.de.menu.main]]
      identifier = "about"
      name = "Über"
      url = "/about/"
      weight = 20

  [languages.en]
    languageCode = 'en-US'
    languageName = 'English'
    title = 'tobiasschuerg.de'
    weight = 2
    [languages.en.params]
      description = "Collecting digital dust."
    [[languages.en.menu.main]]
      identifier = "projects"
      name = "Projects"
      url = "/"
      weight = 10
    [[languages.en.menu.main]]
      identifier = "about"
      name = "About"
      url = "/about/"
      weight = 20
